models/user.py
from database.db import db


class UserModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email=db.Column(db.String(30),nullable=False)
    password=db.Column(db.String(255))
    role = db.Column(db.String(20), default='user')

    def __init__(self,email,password , role):
        self.email=email
        self.password=password
        self.role = role

    def __repr__(self):
        return f"{self.id}"

app.py
from flask import Flask
from routes.auth_route import auth_router
from routes.user_route import user_router
from routes.pages_route import page_router
from flask_sqlalchemy import SQLAlchemy
from database.db import db
from database import config
from flask_jwt_extended import JWTManager



# instance Flask Claskk
app=Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = config.DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['JWT_TOKEN_LOCATION'] = ['cookies']
app.config['JWT_COOKIE_SECURE'] = False
app.config['JWT_ACCESS_COOKIE_PATH'] = '/api/'
app.config['JWT_COOKIE_CSRF_PROTECT'] = True
app.config['JWT_SECRET_KEY'] = 'sudsafadsfasdf§"$"§ret'  # Change this!


# instance JWTManager,SQLAlchemy
JWTManager(app)
SQLAlchemy(app)


# instance routes 
app.register_blueprint(auth_router)
app.register_blueprint(user_router)
app.register_blueprint(page_router)


# Init DB
db.init_app(app)
with app.app_context(): 
    db.create_all()

# run app Locally
if __name__ == "__main__":
    app.run()

routes/auth_route.py
from flask import Blueprint, request, jsonify, render_template, make_response, redirect, url_for
from security import secur_pass
from models.user import UserModel

from flask_jwt_extended import (
    JWTManager, jwt_required, create_access_token,
    create_refresh_token,
    get_jwt_identity, set_access_cookies,
    set_refresh_cookies, unset_jwt_cookies
)

from database.db import db


auth_router = Blueprint('auth', __name__, url_prefix='/auth')


@auth_router.route('/register', methods=['GET'])
def get_register():
    return render_template('/auth/register.html')


@auth_router.route('/login', methods=['GET'])
def get_login():
    return render_template('/auth/login.html')




@auth_router.route('/register', methods=['POST'])
def create_user():

    email = request.form['email']
    password = request.form['password']
    user_exist = UserModel.query.filter_by(email=email).first()
    if not user_exist:
        try:
            hashed_custid = secur_pass.get_password_hash(password)
            new_user = UserModel(
                email=email, password=hashed_custid, role="user")
            db.session.add(new_user)
            db.session.commit()
        except:
            return "some error"

        return render_template('/auth/register.html', contacts="Your account created successfuly!")
    else:
        return render_template('/auth/register.html', contacts="Email or password ist not correct!!")


# @auth_router.route("/login", methods=["POST"])
# def create_token():
#     email = request.form['email']
#     password = request.form['password']
#     user_exist = UserModel.query.filter_by(email=email).first()

#     if not user_exist.email or not secur_pass.verify_password(password, user_exist.password):
#         print('not found')
#         return jsonify("Wrong password"), 401

#     access_token = create_access_token(identity=email)
#     refresh_token = create_refresh_token(identity=email)
#     resp = jsonify({'login': True})
#     set_access_cookies(resp, access_token)
#     set_refresh_cookies(resp, refresh_token)
#     return resp, 200

@auth_router.route("/login", methods=["POST"])
def create_token():
    email = request.form['email']
    password = request.form['password']
    user_exist = UserModel.query.filter_by(email=email).first()

    if not user_exist.email or not secur_pass.verify_password(password, user_exist.password):
        print('not found')
        return jsonify("Wrong password"), 401

    access_token = create_access_token(
        identity={"email": user_exist.email, "role": user_exist.role})
    # refresh_token = create_refresh_token(identity=user_exist.email)
    resp = make_response(redirect(url_for('page.index')))

    set_access_cookies(resp, access_token)
    # set_refresh_cookies(resp, refresh_token)
    return resp

routes/pages_route.py
from flask import Blueprint, request, jsonify,render_template




page_router = Blueprint('page', __name__,)



@page_router.route('/')
def index():
    return render_template('/pages/index.html')


@page_router.route('/contact')
def contact():
    return render_template('/pages/contact.html')

routes/user_route.py
from flask import Blueprint, render_template, jsonify, make_response, url_for,redirect
from flask_jwt_extended import (get_jwt_identity,jwt_required)
from models.user import UserModel



user_router = Blueprint('user', __name__, url_prefix='/api')


# Wirite your protect endpoint here ---------------------

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='/bootstrap/css/bootstrap.min.css')}}" />
    <link rel="stylesheet" href="{{url_for('static', filename='/fontawesome/css/all.css')}}" />
    <title>Document</title>
</head>

<body>

    {% include '/partials/_navbar.html' with context %}


    <main>
        <section class="position-relative overflow-hidden pt-5 pt-lg-3">
            <figure class="position-absolute top-50 start-0 translate-middle-y ms-n7 d-none d-xxl-block">
                <img class="opacity-25" src="{{ url_for('static', filename = 'img/graph.png') }}" width="280"
                    height="280" alt="previous" title="Previous" border="0">
            </figure>

            <figure class="position-absolute top-50 end-0 translate-middle-y mt-5 me-n5 d-none d-xxl-inline-flex">
                <img class="opacity-25" src="{{ url_for('static', filename = 'img/graph.png') }}" width="280"
                    height="280" alt="previous" title="Previous" border="0">
            </figure>
            {% block content %}

            {% endblock %}
        </section>
    </main>



    {% include '/partials/_footer.html' with context %}


</body>

</html>

templates/pages/contact.html
{% extends 'base.html' %}


{% block content %}
<!-- Contact Section -->
<section class="page-section jumbotron d-flex align-items-center min-vh-100" id="contact" >
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0">Let's Get In Touch!</h2>
                <hr class="divider">
                <p class="text-muted mb-5">We would love to hear from you!!</p>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6">
 
                <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                    <!-- Name input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" data-sb-can-submit="no">
                        <label for="name">Full name</label>
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <!-- Email address input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" data-sb-can-submit="no">
                        <label for="email">Email address</label>
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                    <!-- Phone number input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" data-sb-can-submit="no">
                        <label for="phone">Phone number</label>
                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required" data-sb-can-submit="no"></textarea>
                        <label for="message">Message</label>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                    <!-- Submit success message-->
                    <!---->
                    <!-- This is what your users will see when the form-->
                    <!-- has successfully submitted-->
                    <div class="d-none" id="submitSuccessMessage">
                        <div class="text-center mb-3">
                            <div class="fw-bolder">Form submission successful!</div>
                            To activate this form, sign up at
                            <br>
                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                        </div>
                    </div>
                    <!-- Submit error message-->
                    <!---->
                    <!-- This is what your users will see when there is-->
                    <!-- an error submitting the form-->
                    <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                    <!-- Submit Button-->
                    <div class="d-grid"><button class="btn btn-primary btn-xl disabled" id="submitButton" type="submit">Submit</button></div>
                </form>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-4 text-center mb-5 mb-lg-0">
                <i class="bi-phone fs-2 mb-3 text-muted"></i>
                <div>+88 (555) 123-1067</div>
            </div>
        </div>
    </div>
</section>
<!-- End Contact Section -->
{% endblock %}

templates/pages/dashboard.html
{% extends 'base.html' %}

{% block title %}
Flask SQLAlchemy CRUD
{% endblock %}

{% block content %}


<h1> Dashbord Page</h1>

{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}

{% block title %}
  Flask SQLAlchemy CRUD 
{% endblock %}

{% block content %}


<main>
    <section class="position-relative overflow-hidden pt-5 pt-lg-3">
        <figure class="position-absolute top-50 start-0 translate-middle-y ms-n7 d-none d-xxl-block">
            <img class="opacity-25" src="{{ url_for('static', filename = 'img/graph.png') }}" width="280" height="280" alt="previous"
                title="Previous" border="0">
        </figure>

        <figure class="position-absolute top-50 end-0 translate-middle-y mt-5 me-n5 d-none d-xxl-inline-flex">
            <img class="opacity-25" src="{{ url_for('static', filename = 'img/graph.png') }}" width="280" height="280" alt="previous"
                title="Previous" border="0">
        </figure>

        <div class="container ">
            <div class="row align-items-start h-100  p-5">
                <div class="col-lg-7 col-xl-4 position-relative z-index-1 text-center text-lg-start pt-5 ">
                    <p class="fs-1"><kbd class="text-warning">Flask Web APP API</kbd> </p>
                    <p class="fs-3"> with MySQL and Token</p>
                    <p>Flask ist ein vom österreichischen Programmierer Armin Ronacher in Python geschriebenes
                        Webframework.
                        Der Fokus von Flask liegt auf Erweiterbarkeit und guter Dokumentation. Die einzigen
                        Abhängigkeiten
                        sind Jinja2, eine Template-Engine, und Werkzeug, eine Bibliothek zum Erstellen von
                        WSGI-Anwendungen.
                    </p>

                    <ul class="list-inline position-relative justify-content-center justify-content-lg-start mb-4">
                        <li class="list-inline-item me-2"> <i class="fa-solid fa-square-check pe-2"></i>Learn with
                            experts
                        </li>
                        <li class="list-inline-item me-2"> <i class="fa-solid fa-square-check  pe-2"></i>Get
                            certificate
                        </li>
                        <li class="list-inline-item"> <i class="fa-solid fa-square-check  pe-2"></i>Get membership
                        </li>
                    </ul>

                </div>
                <div class="col-lg-7 col-xl-8 d-flex  justify-content-center  position-relative">
                    <img src="{{ url_for('static', filename = 'img/idee.jpg') }}" width="80%" height="80%"
                        alt="previous" title="Previous" border="0">


                </div>


                <div class="row align-items-center g-4 mt-5">

                    <div class="col-sm-6 col-xl-3">
                        <div
                            class="d-flex justify-content-center align-items-center p-4 bg-warning  rounded-3">
                            <span>
                                <i class="fa-light fa-tv"></i>
                            </span>
                               <div class="ms-4 h6 fw-normal mb-0">
                                <div class="d-flex">
                                    <h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0"
                                        data-purecounter-end="10" data-purecounter-delay="200"
                                        data-purecounter-duration="0">10</h5>
                                    <span class="mb-0 h5">K</span>
                                </div>
                                <p class="mb-0">Online Courses</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-xl-3">
                        <div
                            class="d-flex justify-content-center align-items-center p-4 bg-warning bg-opacity-15 rounded-3">
                            <i class="fa-duotone fa-user"></i>
                                <div class="ms-4 h6 fw-normal mb-0">
                                <div class="d-flex">
                                    <h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0"
                                        data-purecounter-end="10" data-purecounter-delay="200"
                                        data-purecounter-duration="0">10</h5>
                                    <span class="mb-0 h5">K</span>
                                </div>
                                <p class="mb-0">Certified Courses</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-xl-3">
                        <div
                            class="d-flex justify-content-center align-items-center p-4 bg-warning bg-opacity-15 rounded-3">
                            <i class="fa-light fa-tv"></i>
                            <div class="ms-4 h6 fw-normal mb-0">
                                <div class="d-flex">
                                    <h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0"
                                        data-purecounter-end="10" data-purecounter-delay="200"
                                        data-purecounter-duration="0">10</h5>
                                    <span class="mb-0 h5">K</span>
                                </div>
                                <p class="mb-0">Online Studentss</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-xl-3">
                        <div
                            class="d-flex justify-content-center align-items-center p-4 bg-warning bg-opacity-15 rounded-3">
                            <i class="fa-light fa-tv"></i>
                            <div class="ms-4 h6 fw-normal mb-0">
                                <div class="d-flex">
                                    <h5 class="purecounter mb-0 fw-bold" data-purecounter-start="0"
                                        data-purecounter-end="10" data-purecounter-delay="200"
                                        data-purecounter-duration="0">10</h5>
                                    <span class="mb-0 h5">K</span>
                                </div>
                                <p class="mb-0">Expert Tutors</p>
                            </div>
                        </div>
                    </div>



                </div>

            </div>
        </div>

    </section>



    <section class="page-section" id="services">
        <div class="container px-4 px-lg-5">
            <h2 class="text-center mt-0">At Your Service</h2>
            <hr class="divider">
            <div class="row gx-4 gx-lg-5">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="fa-solid fa-gem"></i></div>
                        <h3 class="h4 mb-2">Sturdy Themes</h3>
                        <p class="text-muted mb-0">Our themes are updated regularly to keep them bug free!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="fa-solid fa-laptop"></i></div>
                        <h3 class="h4 mb-2">Up to Date</h3>
                        <p class="text-muted mb-0">All dependencies are kept current to keep things fresh.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="fa-solid fa-earth-americas"></i></div>
                        <h3 class="h4 mb-2">Ready to Publish</h3>
                        <p class="text-muted mb-0">You can use this design as is, or you can make changes!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="fa-solid fa-heart-circle-bolt"></i></div>
                        <h3 class="h4 mb-2">Made with Love</h3>
                        <p class="text-muted mb-0">Is it really open source if it's not made with love?</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>



{% endblock %}

templates/partials/_footer.html
<footer class="text-center text-lg-start fixed-bottom">
  <!-- Grid container -->
            <div class="container p-4 pb-0">
              <!-- Section: Form -->
              <section class="">
                <form action="">
                  <!--Grid row-->
                  <div class="row d-flex justify-content-center">
                    <!--Grid column-->
                    <div class="col-auto">
                      <p class="pt-2">
                        <strong>Sign up for our newsletter</strong>
                      </p>
                    </div>
                    <!--Grid column-->
          
                    <!--Grid column-->
                    <div class="col-md-5 col-12">
                      <!-- Email input -->
                      <div class="form-outline mb-4">
                        <input type="email" id="form5Example27" class="form-control" />
                      </div>
                    </div>
                    <!--Grid column-->
          
                    <!--Grid column-->
                    <div class="col-auto">
                      <!-- Submit button -->
                      <button type="submit" class="btn btn-dark mb-4">
                        Subscribe
                      </button>
                    </div>
                    <!--Grid column-->
                  </div>
                  <!--Grid row-->
                </form>
              </section>
              <!-- Section: Form -->
            </div>
            <!-- Grid container -->
          
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
              © 2023 Copyright:
              <a class="text-dark" href="#">mbosoft</a>
            </div>
            <!-- Copyright -->
          </footer>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary  ">
    <div class="container-fluid">


        <a class="navbar-brand d-flex justify-content-center" href="#">
            <img src="{{ url_for('static', filename = 'img/mbosoft.png') }}" width="30" height="30" alt="previous"
                title="Previous" border="0">
            <span class="ps-2">MBOSOFT</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon justify-content-center "></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarScroll">

            <ul class="navbar-nav mx-auto">
                <li class="nav-item active text-center">
                    <a href="/" aria-current="page" class="nav-link">Home</a>
                </li>
                <li class="nav-item text-center">
                    <a class="nav-link" href="#">about</a>
                </li>
                <li class="nav-item text-center">
                    <a href="/contact" aria-current="page" class="nav-link">Contact</a>
                </li>
                <li class="nav-item text-center">
                    <a class="nav-link" href="#">Online Curse</a>
                </li>
                <li class="nav-item text-center">
                    <a class="nav-link" href="#">E-Learning</a>
                </li>
                <li class="nav-item text-center">
                    <a class="nav-link" href="{{ url_for('user.get_dashbord') }}">Dashbord</a>
                </li>
            </ul>



            <div class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <a class="btn btn-outline-dark" href="{{ url_for('auth.get_login') }}">Login</a>



            </div>
        </div>

    </div>
</nav>

templates/user/dashbord.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>secret</h1>
    
</body>
</html>